### ISSUE TITLE
Client v2 Checklist

### ISSUE THREAD

**Issue by aradmargalit** [aradmargalit/phobos#55]
We're doing a major rework of the client. Once all boxes are checked, we're good to go:
- [ ] Typescript
- [ ] 90% test coverage
- [ ] Hooks for all data fetching
- [ ] No reliance on antd
- [ ] Formik for form management
- [ ] Lighthouse 80 or better across the board
